### ISSUE TITLE
[PE-D][Tester D] findtask title

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T14-1/tp#110]
findtask title displays all tasks and people associated to those tasks
findtask task does the same thing.
![image.png](https://raw.githubusercontent.com/Wyrkx/ped/main/files/aecca42b-b31d-4b70-85d1-5ecfffe0858f.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Wyrkx/ped#1

**Comment by howenyap** [comment]
Resolved
