### ISSUE TITLE
[PE-D][Tester A] Incomplete text display

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T14-1/tp#111]
Full address cannot be viewed if length of address exceeds one line, even when the column on the left has been minimized. 

**See person at index 7**
![image.png](https://raw.githubusercontent.com/JiaXinEu/ped/main/files/e7d8b1a5-479f-4f4c-b176-ae38cd7cc62a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: JiaXinEu/ped#1

**Comment by yiwern5** [comment]
#156 #155 #151
