### ISSUE TITLE
[PE-D][Tester C] findtask only checks tasks that are not done

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T14-1/tp#122]
The KEYWORD in findtask only matches against tasks that are 'not done' and doesn't check marked tasks. If this is its intended functionality then it should be mentioned in the UG.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: VatsalVitosh/ped#4

**Comment by yiwern5** [comment]
#142

**Comment by howen02** [comment]
Resolved.

**Comment by howenyap** [comment]
Resolved
