### ISSUE TITLE
[PE-D][Tester E] Add command is not allowed even with different email

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T14-1/tp#134]
Two person with the same name, phone number, address, but different email will be resulted in *This person already exists in the address book*

add n/John Doe p/98765432 e/oldemail@example.com a/same address d/Business Development t/friends t/owesMoney eff/80
add n/John Doe p/98765432 e/newemail@example.com a/same address d/Business Development t/friends t/owesMoney eff/80

![image.png](https://raw.githubusercontent.com/jinhanfromNUS/ped/main/files/45b1c328-51a1-4713-961d-6c466b062b18.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jinhanfromNUS/ped#5

**Comment by laybach** [comment]
It is not a bug as the intention was that 2 person cannot have the same name even though the other fields are the same. The specifications will be reflected in the user guide.
