### ISSUE TITLE
[PE-D][Tester B] Mark command side effect not in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T14-1/tp#139]
![Screenshot 2024-04-05 at 4.49.14 PM.png](https://raw.githubusercontent.com/SimHanKiong/ped/main/files/88509cc3-7d51-4622-81f4-f3cc35cfe9f7.png)

Side effect of changing efficiency to 0% after marking task as done not specified in UG

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: SimHanKiong/ped#12

**Comment by howen02** [comment]
Updated user guide to include side effects

**Comment by howenyap** [comment]
Updated user guide to include side effects.
