### ISSUE TITLE
[PE-D][Tester E] Duplicate person only checks name.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T14-1/tp#140]
I did not check the code, but it seems that EffiTrack only checks the Name when it comes to duplication.

add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 d/Business Development t/friends t/owesMoney eff/80
add n/John Doe p/12345678 e/Howen@pgpr a/block9 d/Other department t/owesMonies eff/50

![image.png](https://raw.githubusercontent.com/jinhanfromNUS/ped/main/files/7d026380-c567-45bf-95e0-56eecf3aceff.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: jinhanfromNUS/ped#7

**Comment by laybach** [comment]
We do not allow duplicate person with the same name only. It will be reflected in our user guide.
